CREATE TABLE IF NOT EXISTS kb_document (
    id BIGINT NOT NULL COMMENT '主键ID',
    document_id VARCHAR(64) NOT NULL COMMENT '业务文档ID(UUID)',
    file_name VARCHAR(255) NOT NULL COMMENT '文件名',
    file_ext VARCHAR(32) DEFAULT '' COMMENT '文件扩展名',
    mime_type VARCHAR(128) DEFAULT NULL COMMENT 'MIME类型',
    file_size BIGINT NOT NULL DEFAULT 0 COMMENT '文件大小(字节)',
    s3_bucket VARCHAR(128) NOT NULL COMMENT 'S3桶',
    s3_object_key VARCHAR(512) NOT NULL COMMENT 'S3对象键',
    file_url VARCHAR(1024) DEFAULT NULL COMMENT '文件URL',
    status VARCHAR(32) NOT NULL COMMENT '状态:UNPROCESSED/RUNNING/COMPLETED/FAILED',
    chunk_count INT NOT NULL DEFAULT 0 COMMENT '分片数量',
    vector_count INT NOT NULL DEFAULT 0 COMMENT '向量数量',
    error_message VARCHAR(1000) DEFAULT NULL COMMENT '错误信息',
    created_by VARCHAR(64) NOT NULL COMMENT '创建人',
    updated_by VARCHAR(64) NOT NULL COMMENT '更新人',
    create_time DATETIME NOT NULL COMMENT '创建时间',
    update_time DATETIME NOT NULL COMMENT '更新时间',
    deleted INTEGER DEFAULT 0 COMMENT '逻辑删除',
    PRIMARY KEY (id),
    UNIQUE KEY uk_document_id (document_id),
    KEY idx_status (status),
    KEY idx_update_time (update_time)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='知识库文件表';
